package com.hg.test_project_2;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Product implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Product() {
    }




}